import Navbar from "@/components/Navbar/page";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en" className="dark">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
