import Navbar from "@/components/Navbar/page";
import "./globals.css";
import CategoriesBar from "@/components/Categories/CategoriesBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar />
        <CategoriesBar />
        {children}
      </body>
    </html>
  );
}
